
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PRISMA_MIGRATE_SHADOW_DATABASE_URL=${PRISMA_MIGRATE_SHADOW_DATABASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}
    command: sh -c "npx prisma migrate deploy && npm run start"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPassword123!
      - MSSQL_PID=Express
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P StrongPassword123! -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - sqlserver_data:/var/opt/mssql
    ports:
      - "1433:1433"

volumes:
  sqlserver_data:
    # Persistencia de datos para SQL Server